language: node_js
node_js:
  - "20"

dist: generic

cache:
  directories:
    - ~/.npm
    - ~/.cache

jobs:
  include:
    - stage: install-build
      name: Install And Build
      script:
        - npm install -g yarn
        - yarn init -2
        - yarn tsc -b
        - yarn npm publish