language: node_js
node_js:
  - "20"

dist: jammy

cache:
  directories:
    - ~/.npm
    - ~/.cache

jobs:
  include:
    - stage: install-build
      name: Install And Build
      script:
        - npm install -g yarn
        - yarn set version latest
        - yarn install
        - yarn tsc -b

    - stage: deploy
      name: publish to npmjs.com
      deploy:
        provider: npm
        email: "liletian1231@gmail.com"
        api_token: $npmToken
        cleanup: false
