language: node_js
node_js:
  - "20"

dist: generic

cache:
  yarn: true
  directories:
    - ~/.npm
    - ~/.cache

jobs:
  include:

    - stage: build
      name: Build
      script:
        - yarn tsc -b && yarn npm publish