language: node_js
node_js:
  - "20"

dist: generic

cache:
  directories:
    - ~/.npm
    - ~/.cache

jobs:
  include:
    - stage: install-yarn
      name: Install Yarn
      script:
        - npm install -g yarn
        - yarn init -2

    - stage: build
      name: Build
      script:
        - yarn tsc -b && yarn npm publish