language: node_js
node_js:
  - "20"

dist: jammy

cache:
  directories:
    - ~/.npm
    - ~/.cache

jobs:
  include:
    - stage: install-build-publish
      name: Install And Build
      script:
        - npm install -g yarn
        - yarn install
        - yarn tsc -b
        - ls lib/
      before_deploy:
        - npm install -g npm@9
        - ls -a
      # deploy:
      #   provider: npm
      #   email: "liletian1231@gmail.com"
      #   api_token: $npmToken
      #   cleanup: false