language: node_js
node_js:
  - "20"

dist: generic

cache:
  directories:
    - ~/.npm
    - ~/.cache

jobs:
  include:

    - stage: install
      name: Install
      script:
        - npm run install

    - stage: build
      name: Build
      script:
        - npm run build